#server:
#  port:9092
spring:
  application:
    name: BOOK-SERVICE
  cloud:
    config:
      uri:
        - http://localhost:9196
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2